branch-defaults:
 main:
   environment: Env-Prod
 uat:
   environment: Env-UAT
global:
 application_name: SysDev-HelloWorld
 default_ec2_keyname: null
 default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/PHP 7.4 running on 64bit Amazon Linux 2
 default_region: eu-west-2
 include_git_submodules: true
 instance_profile: null
 platform_name: null
 platform_version: null
 profile: null
 sc: git
 workspace_type: Application
