version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm version
      - run:
          name: Run tests
          command: npm version
  deploy-aws:
    working_directory: ~/app
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Branch to process
          working_directory: ~/app/.ebextensions/
          command: ls
      - run:
          name: Apply environment config file
          working_directory: ~/app/.ebextensions/
          command: mv "env-prod.config-option" "env-${CIRCLE_BRANCH}.config"
      - run:
          name: Branch to process
          working_directory: ~/app/.ebextensions/
          command: ls
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: 'sudo pip install awsebcli --upgrade'
      - run:
          name: Deploying application to Elastic Beanstalk
          command: eb deploy --staged

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-aws:
          requires:
            - test
