version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm version
      - run:
          name: Run tests
          command: npm version
  deploy-aws:
    working_directory: ~/app
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Applying AWS profiles
          command: cp .circleci/aws-config ~/.aws/config
      - run:
          name: Applying ElasticBeanstalk environment config file
          working_directory: ~/app/.ebextensions/
          command: mv "~env-${CIRCLE_BRANCH}.config" "env-${CIRCLE_BRANCH}.config"
      - run:
          name: Updating JavaScript config file
          command: cd .circleci && chmod +x ${CIRCLE_BRANCH}-js-config.sh && ./${CIRCLE_BRANCH}-js-config.sh
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Deploying application to Elastic Beanstalk
          command: eb deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-aws:
          requires:
            - test
